-- +goose Up
-- +goose NO_TRANSACTION

ALTER TABLE products ADD COLUMN IF NOT EXISTS is_hot BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_sale BOOLEAN NOT NULL DEFAULT FALSE;
-- +goose Down
-- +goose NO_TRANSACTION

ALTER TABLE products DROP COLUMN IF EXISTS is_sale;
ALTER TABLE products DROP COLUMN IF EXISTS is_hot;
